[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Coverage configuration
coverage = true
coverage_threshold = 90

# Gas reports
gas_reports = ["Vault", "ProposalVaultManager", "SchemaManager", "VaultPermissions", "VaultSignatureValidator"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
